### PR TITLE
feat: add horizontal scrolling

### LINKED ISSUE #118: Logitech MX Master side (horizontal) scroll wheel
I have a logitech plugged in and all the buttons work except the horizontal scroll.

I'll happily tackle this once I can figure out how to build for arm from my local setup.

Note: this is a placeholder issue for myself until I get time to investigate over a weekend. I will update this issue with more detail soon.

### PR DESCRIPTION
**Pull request by jalmeroth**
Fixes #118 (I guess)

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
Built and can confirm this works with a MX Master 3. Thank you!

**Comment by cornfeedhobo** [comment]
@jalmeroth any instructions on how I could invert scroll direction? I see that newer firmware versions now implement the config as a web interface, but maybe something in `user_config.h` to start?

**Comment by jalmeroth** [comment]
> @jalmeroth any instructions on how I could invert scroll direction? I see that newer firmware versions now implement the config as a web interface, but maybe something in ~`user_config.h` to start~ `mouse.c`?

I think this is worth a different issue. But how would you do this normally? In the Logitech Configuration Software? If so, I think it would be worth checking out to enable this functionality with DH too.

**Comment by cornfeedhobo** [comment]
@jalmeroth I've never used the Logitech configuration software. KDE only offers reversing all scrolling, vertical and horizontal, but not individually. Oh well, maybe I'll get used to it. I agree, best left as a follow up issue. Great work!

**Comment by hrvach** [comment]
@jalmeroth this looks great, thank you!

**Comment by hrvach** [comment]
Testing a bit before releasing the new version.

**Pull request merged**
